[package]
name = "taneleer"
authors = ["Stanislav Shmarov <github@snarpix.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
dbus = "0.9.5"
dbus-crossroads = "0.5.0"
dbus-tokio = "0.7.5"
futures = "0.3.21"
async-trait = "0.1.56"
tokio = { version = "1.19.0", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["sync"] }
sqlx = { version = "0.5.13", features = ["sqlite", "runtime-tokio-native-tls"] }
serde = "1.0.137"
serde_with = "1.14.0"
serde_derive = "1.0.137"
serde_yaml = "0.8.24"
