[package]
name = "taneleer"
authors = ["Stanislav Shmarov <github@snarpix.com>"]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
repository = "https://github.com/Snarpix/taneleer"
description = "Build artifacts storage service"

[dependencies]
dbus = "0.9.5"
dbus-crossroads = "0.5.1"
dbus-tokio = "0.7.5"
futures = "0.3.21"
async-trait = "0.1.56"
tokio = { version = "1.19.2", features = ["full"] }
tokio-stream = { version = "0.1.9", features = ["sync"] }
sqlx = { version = "0.6.0", features = ["sqlite", "runtime-tokio-native-tls", "uuid"] }
serde = "1.0.137"
serde_with = "1.14.0"
serde_derive = "1.0.137"
serde_yaml = "0.8.24"
uuid = { version = "1.1.2", features = ["v4", "fast-rng", "macro-diagnostics"] }
hex = "0.4.3"
url = "2.2.2"
log = { version = "0.4.17", features = ["max_level_trace", "release_max_level_info"] }
env_logger = "0.9.0"
sha2 = "0.10.2"
bytes = "1.1.0"
axum = { version = "0.6.0-rc.1", features = ["headers"] }
regex = "1.6.0"
lazy_static = "1.4.0"
