rpc:
  - type: wsjsonrpc
    address: "::"
    port: 5002

backends:
  fs_test:
    type: fs
    root_path: storage_root

  docker_test:
    type: docker_registry
    root_path: docker_root

frontends:
  - type: docker_registry
    address: "::"
    hostname: host.docker.internal
    port: 5001
    default_backend: docker_test

storage:
  type: sqlite
  path: storage.db
