frontends:
  - type: dbus
    dbus_name: com.snarpix.taneleer
    bus: session

backends:
  fs_test:
    type: fs
    root_path: storage_root
    proxies:
      http: 
        type: rewrite
        from: file:///Users/snarpix/Documents/taneleer/storage_root
        to: http://localhost:3000/storage_root

storage:
  type: sqlite
  path: storage.db
